
default:
  stackName: <prefix>-cumulus
  stackNameNoDash: <Prefix>Cumulus

  apiStage: dev

  vpc:
    vpcId: '{{VPC_ID}}'
    subnets:
      - '{{AWS_SUBNET}}'

  ecs:
    instanceType: t2.nano
    desiredInstances: 0
    availabilityZone: us-east-1a

  system_bucket: '{{buckets.internal.name}}'

  buckets:
    internal:
      name: se-tim-internal
      type: internal
    protected:
      name: se-tim-protected
      type: protected
    public:
      name: se-tim-public-data
      type: public

  iams:
    ecsRoleArn: arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-ecs
    lambdaApiGatewayRoleArn: arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-lambda-api-gateway
    lambdaProcessingRoleArn: arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-lambda-processing
    stepRoleArn: arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-steprole
    instanceProfile: arn:aws:iam::{{AWS_ACCOUNT_ID}}:instance-profile/{{stackName}}-ecs
    distributionRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-distribution-api-lambda'
    scalingRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{stackName}}-scaling-role'

  urs_url: https://uat.urs.earthdata.nasa.gov/ #make sure to include the trailing slash

  # if not specified the value of the apigateway backend endpoint is used
  # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

  # if not specified the value of the apigateway dist url is used
  api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  # URS users who should have access to the dashboard application.
  users:
    - username: lfrederick

lf-template: 
  stackName: lf-template
  stackNameNoDash: LfTemplate

  es: null

