default:
  prefix: nasa-map
  stackName: '{{prefix}}-iam'
  authorizor: false
  capabilities:
    - CAPABILITY_NAMED_IAM

  system_bucket: cumulus-map-internal

  buckets:
    internal:
      name: cumulus-map-internal
      type: internal

  params:
     - name: ResourcePrefix
       value: '{{prefix}}'
