default:
  prefix: template-cumulus
  stackName: template-cumulus-iam
  authorizor: false
  capabilities:
    - CAPABILITY_NAMED_IAM

  system_bucket: '{{buckets.internal.name}}'

  buckets:
    internal:
      name: se-tim-internal
      type: internal
    protected:
      name: se-tim-protected
      type: protected
    public:
      name: se-tim-public-data
      type: public

  params:
     - name: ResourcePrefix
       value: '{{prefix}}'

lf-template: 
  prefix: lf-template
  stackName: lf-template-iam

